modLoader="javafml"
loaderVersion="[37,)"
license="MIT License"
[[mods]]
modId="proflock"
version="${file.jarVersion}"
displayName="Profession Lock"
displayURL="https://www.curseforge.com/minecraft/mc-mods/profession-lock"
logoFile="logo.png"
authors="Lupicus, MacTso"
description='''Profession Lock Mod'''
[[dependencies.proflock]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.proflock]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
