modLoader="javafml"
loaderVersion="[44,)"
license="MIT License"
[[mods]]
modId="proflock"
version="${file.jarVersion}"
displayName="Profession Lock"
displayURL="https://www.curseforge.com/minecraft/mc-mods/profession-lock"
displayTest="IGNORE_SERVER_VERSION"
logoFile="logo.png"
authors="Lupicus, MacTso"
description='''Profession Lock Mod'''
[[dependencies.proflock]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.proflock]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
